version: "3"

services:

  runtime-setup:
    image: swift-cassandra-client:20.04-5.5
    build:
      args:
        ubuntu_version: "focal"
        swift_version: "5.5"

  build:
    image: swift-cassandra-client:20.04-5.5

  test:
    image: swift-cassandra-client:20.04-5.5

  shell:
    image: swift-cassandra-client:20.04-5.5
