version: "3"

services:

  runtime-setup:
    image: swift-cassandra-client:20.04-5.6
    build:
      args:
        ubuntu_version: "focal"
        swift_version: "5.6"

  build:
    image: swift-cassandra-client:20.04-5.6

  test:
    image: swift-cassandra-client:20.04-5.6

  shell:
    image: swift-cassandra-client:20.04-5.6
