version: "3"

services:

  runtime-setup:
    image: swift-cassandra-client:20.04-5.4
    build:
      args:
        ubuntu_version: "focal"
        swift_version: "5.4"

  build:
    image: swift-cassandra-client:20.04-5.4

  test:
    image: swift-cassandra-client:20.04-5.4

  shell:
    image: swift-cassandra-client:20.04-5.4
